apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/managed-by: kustomize
  name: openshift-updateservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: updateservice-operator
  annotations:
    kubernetes.io/description: |
      This OpenShift Update Service operator Deployment reconciles local UpdateServices into more fundamental Kubernetes
      and OpenShift resources like Cincinnati Deployments and Routes, and it reports the status of those components in 
      the UpdateService status.
spec:
  replicas: 1
  selector:
    matchLabels:
      name: updateservice-operator
  template:
    metadata:
      labels:
        name: updateservice-operator
    spec:
      serviceAccountName: updateservice-operator
      containers:
        - name: updateservice-operator
          image: controller:latest
          imagePullPolicy: Always
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "updateservice-operator"
            - name: RELATED_IMAGE_OPERAND
              value: "quay.io/cincinnati/cincinnati:latest"
