apiVersion: apps/v1
kind: Deployment
metadata:
  name: updateservice-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: updateservice-operator
  template:
    metadata:
      labels:
        name: updateservice-operator
    spec:
      serviceAccountName: updateservice-operator
      containers:
        - name: updateservice-operator
          image: quay.io/updateservice/updateservice-operator:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "updateservice-operator"
            - name: OPERAND_IMAGE
              value: "quay.io/updateservice/updateservice:latest"
