apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: updateservice-operator
  name: updateservice-operator-metrics
  namespace: openshift-update-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    control-plane: updateservice-operator
