kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: updateservice-operator
subjects:
- kind: ServiceAccount
  name: updateservice-operator
  namespace: openshift-update-service
roleRef:
  kind: Role
  name: updateservice-operator
  apiGroup: rbac.authorization.k8s.io
