apiVersion: apps/v1
kind: Deployment
metadata:
  name: cincinnati-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cincinnati-operator
  template:
    metadata:
      labels:
        name: cincinnati-operator
    spec:
      serviceAccountName: cincinnati-operator
      containers:
        - name: cincinnati-operator
          image: local.registry:5000/rhallise/cincinnati-operator
          command:
          - cincinnati-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cincinnati-operator"
            - name: OPERAND_IMAGE
              value: "quay.io/cincinnati/cincinnati:latest"
