apiVersion: updateservice.operator.openshift.io/v1
kind: UpdateService
metadata:
  name: disconnected-updateservice
spec:
  replicas: 1
  registry: "quay.io"
  repository: "jottofar/updateservice-graph-data-container"
  graphDataImage: "quay.io/jottofar/updateservice-graph-data-container:latest"
